#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EntradaCamionetas.Resource", IsApplication=true)]

namespace EntradaCamionetas
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int cerrar = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int exito = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int logo = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int nota = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int pedido = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int producto = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int registro = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int salir = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int warning = 2130771976;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020004
			public const int about_app = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int app_logo = 2130837509;
			
			// aapt resource value: 0x7F020000
			public const int Asignar = 2130837504;
			
			// aapt resource value: 0x7F020006
			public const int btnbclose = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int btnlogin = 2130837511;
			
			// aapt resource value: 0x7F020001
			public const int Destino = 2130837505;
			
			// aapt resource value: 0x7F02000A
			public const int fechacaptura = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int fechafin = 2130837515;
			
			// aapt resource value: 0x7F020008
			public const int fechaInicio = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int fechaInicioca = 2130837513;
			
			// aapt resource value: 0x7F02000C
			public const int gvCtrl = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int imgPers = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int linearLayout1 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int linearLayoutHorizontal = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int spinner1 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int spinner2 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int spinner3 = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int spinner4 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int spinner5 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int spinner6 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int spinner7 = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int spinnerx4 = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int tab_icon = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int tab_title = 2130837529;
			
			// aapt resource value: 0x7F020002
			public const int TempFin = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int TempIni = 2130837507;
			
			// aapt resource value: 0x7F02001A
			public const int textView3 = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int totalcapturado = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int totalsolicitado = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int txtAge = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int txtName = 2130837534;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int AgregarEntrada = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int AsignarPedidos = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int cerrarcamioneta = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int custGridViewItem = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int listapedidospendientes = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int TabLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int tab1_text = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int tab2_text = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int tab3_text = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
